language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - mkdir $VIRTUAL_ENV/var

script:
  - python manage.py migrate
  - coverage run manage.py test
  - flake8 pubbot

after_success:
  - coveralls
