language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - mkdir $VIRTUAL_ENV/var

script:
  - pubbot migrate
  - coverage run $(which pubbot) test
  - flake8 pubbot

after_success:
  - coveralls
