language: python
python:
  - "3.4"

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

services:
  - redis-server

install:
  - pip wheel --find-links=$HOME/wheelhouse -r requirements.txt --wheel-dir=$HOME/wheelhouse
  - pip install --no-index --find-links=$HOME/wheelhouse -r requirements.txt
  - mkdir $VIRTUAL_ENV/var

script:
  - pubbot migrate
  - coverage run $(which pubbot) test
  - flake8 pubbot

after_success:
  - coveralls
